spring:
  application:
    name: base-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base-api
    username: apiCM
    password: apiCM123

  jpa:
    hibernate:
      # Options:  None, Validate, Update, Create, Create-Drop
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Log SQL statements
logging:
  level:
    org.hibernate.SQL: OFF

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 600000 # 600000 = 10min # 3600000 1 hour (60 minutes * 60 seconds * 1000 milliseconds)
