spring:
  application:
    name: base-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base-api
    username: apiCM
    password: apiCM123

  jpa:
    hibernate:
      # Options:  None, Validate, Update, Create, Create-Drop
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Log SQL statements
logging:
  level:
    org.hibernate.SQL: OFF
    org.springframework.security: DEBUG

server:
  servlet:
    context-path: /api

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration: 86400000 # 1 day
    refresh-token:
      expiration: 604800000 # 7 days
